version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: client/Dockerfile # <--- Le decimos dónde está el Dockerfile
    container_name: boda-frontend
    ports:
      - "8081:80"
    # depends_on:
    # - backend
    restart: always